name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'devboard-backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy backend files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "devboard-backend/*"
          target: "/home/ubuntu/devboard-backend"
          strip_components: 1

      - name: SSH into EC2 and deploy backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            chmod +x ~/devboard-backend/deploy.sh
            ~/devboard-backend/deploy.sh
